apiVersion: v1
kind: Service
metadata:
  name:  marcin-rtp-service
  namespace: marcin
spec:
  type: NodePort
  selector:
    app: marcin-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000